name: "docker-build"
description: "Build docker image"
inputs:
  use-turnstyle:
    description: Prevent parallel builds
    required: false
    default: "true"
  GITHUB_TOKEN:
    description: Token for accessing GHCR and turnstyle. Set to secrets.GITHUB_TOKEN
    required: true
  platforms:
    description: List of target platforms for docker buildx
    required: false
    default: linux/amd64,linux/arm64,linux/arm/v7
  images:
    description: List of names to tag the image with
    required: false
    default: |
      ghcr.io/${{ github.repository }}
  context:
    description: Context for buildx to use
    required: false
    default: .
  file:
    description: Path of the Dockerfile to use
    required: false
    default: ${{ inputs.context }}/Dockerfile
runs:
  using: composite
  steps:
    - name: Turnstyle
      uses: softprops/turnstyle@v1
      if: ${{ inputs.use-turnstyle }}
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ inputs.images }}
        flavor: |
          latest=auto
        # TODO these probably need some fine-tuning
        tags: |
          type=semver,pattern={{major}}.{{minor}}.{{patch}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=ref,event=pr,prefix=pr-
          type=ref,event=branch,prefix=br-
          type=ref,event=tag,prefix=tag-
          type=sha,prefix=sha-
          type=sha,prefix=sha-,format=long
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.GITHUB_TOKEN }}
    - name: Set up docker cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: buildx-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          buildx-${{ runner.os }}-
          buildx-
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ยง{{ inputs.context }}
        file: ยง{{ inputs.file }}
        platforms: ${{ inputs.platforms }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      # TODO remove me. prevent the cache from growing infinitely
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
